package com.example.fastmart;

import android.app.Application;

import java.util.ArrayList;
import java.util.Arrays;

public class MyApplication extends Application {
    public ArrayList<Item> items;
    public ArrayList<Item> dodItems;
    public ArrayList<Item> cart;
    public ArrayList<Item> wishlist;
    public ArrayList<String> previousSearch;

    public String name;
    public String email;
    public String phNo;
    public String dob;
    public String gender;
    public final String appPhNo = "03107488488";

    @Override
    public void onCreate() {
        super.onCreate();
        items = new ArrayList<>(Arrays.asList(
                new Item(1,
                        R.drawable.headphone1,
                        199.99f, "JBL Headset",
                        "J-123",
                        "Off-White",
                        "Experience immersive sound like never before with the JBL Headset. Designed for comfort and long-lasting use, this headset delivers crystal-clear audio and deep bass, perfect for gaming, music, and calls. Its lightweight, ergonomic design ensures a snug fit, while the built-in microphone lets you communicate effortlessly. Enjoy seamless connectivity, durable build quality, and the signature JBL sound that brings every note to life.",
                        "Headset",
                        10
                ),
                new Item(2,
                        R.drawable.headphone2,
                        299.99f,
                        "Audionic Headset",
                        "A-123",
                        "White",
                        "Experience superior audio with the Audionic Headset, crafted for comfort and clarity. Perfect for music, gaming, and calls, it delivers crisp sound and rich bass. Its lightweight design ensures hours of comfortable use, while the built-in microphone makes communication effortless. Durable, stylish, and reliable, the Audionic headset brings your audio to life.",
                        "Headset",
                        20
                ),
                new Item(3,
                        R.drawable.keyboard1,
                        49.99f,
                        "HP Keyboard",
                        "H-123",
                        "Black",
                        "Enhance your typing experience with the HP Keyboard. Designed for comfort and precision, it delivers responsive keys, smooth performance, and reliable durability for work, gaming, or everyday use. Its sleek design and ergonomic layout make typing effortless, while its sturdy build ensures long-lasting performance.",
                        "Keyboard",
                        30
                ),
                new Item(4,
                        R.drawable.headphone3,
                        399.99f,
                        "Ronin Headset",
                        "R-123",
                        "Purple",
                        "Dive into crystal-clear sound with the Ronin Headset. Engineered for comfort and performance, it delivers powerful bass, crisp highs, and immersive audio for gaming, music, and calls. Its sleek design, durable build, and built-in microphone make it the perfect companion for long listening sessions.",
                        "Headset",
                        10
                ),
                new Item(5,
                        R.drawable.pc3,
                        599.99f,
                        "Acer Gaming PC",
                        "Ac-123",
                        "Glass",
                        "Experience high-performance gaming with the Acer Gaming PC. Powered by an Intel Core i7-12700KF processor, 16GB DDR4 RAM, and an NVIDIA GeForce RTX 4060 GPU, it delivers smooth gameplay and stunning graphics. Enjoy fast storage with a 1TB NVMe SSD and reliable power from a 700W PSU. Its sleek, durable chassis and efficient cooling system make it perfect for long gaming sessions.",
                        "PC",
                        5
                ),
                new Item(6,
                        R.drawable.headphone4,
                        499.99f,
                        "JBL Headset",
                        "J-567",
                        "Black",
                        "Immerse yourself in rich, powerful sound with the JBL Headset. Designed for comfort and style, it delivers deep bass, clear highs, and seamless audio for gaming, music, and calls. With a durable build and built-in microphone, it’s perfect for long listening sessions and effortless communication.",
                        "Headset",
                        60
                ),
                new Item(7,
                        R.drawable.pc1,
                        999.99f,
                        "Asus Gaming PC",
                        "As-123",
                        "White",
                        "Unleash next-level performance with the ASUS Gaming PC. Powered by an Intel Core i7-12700K processor, 16GB DDR4 RAM, and an NVIDIA GeForce RTX 4070 GPU, it delivers smooth gameplay, stunning visuals, and lightning-fast multitasking. Enjoy a 1TB NVMe SSD for ultra-fast storage and a 750W power supply for reliable performance. Designed for gamers, its sleek, durable chassis and optimized cooling system ensure peak performance during intense gaming sessions.",
                        "PC",
                        30
                ),
                new Item(8,
                        R.drawable.keyboard2,
                        99.99f,
                        "Redragon Gaming Keyboard",
                        "R-123",
                        "RCG",
                        "Level up your gaming with the Redragon Gaming Keyboard. Featuring responsive mechanical keys, customizable RGB lighting, and a durable design, it delivers precision and performance for every battle. Ergonomic and stylish, this keyboard ensures comfort during long gaming sessions while giving your setup a striking look.",
                        "Keyboard",
                        7
                ),
                new Item(9,
                        R.drawable.pc2,
                        1999.99f,
                        "MSI Gaming PC",
                        "M-123",
                        "Black",
                        "Dominate every game with the MSI Gaming PC. Equipped with an Intel Core i9-12900K processor, 32GB DDR5 RAM, and an NVIDIA GeForce RTX 4080 GPU, it delivers ultra-smooth gameplay and breathtaking visuals. Store all your games and files on a 2TB NVMe SSD while a 850W power supply ensures stable performance. With a sleek, gamer-focused design and advanced cooling system, the MSI Gaming PC keeps you in the action for hours without compromise.",
                        "PC",
                        8
                ),
                new Item(10,
                        R.drawable.chair3,
                        89.99f,
                        "Basic Study Chair",
                        "C-110",
                        "Blue",
                        "A simple and durable study chair ideal for students. Built with a sturdy plastic frame and comfortable seating, it is lightweight and easy to move. Perfect for study rooms, libraries, and classrooms.",
                        "Chair",
                        150
                ),

                new Item(11,
                        R.drawable.chair4,
                        199.99f,
                        "Executive Leather Chair",
                        "C-410",
                        "Black",
                        "Enhance your workspace with the Executive Leather Chair. Featuring premium leather upholstery, padded armrests, and an adjustable tilt mechanism, it provides luxury and comfort for long office hours.",
                        "Chair",
                        60
                ),

                new Item(12,
                        R.drawable.chair5,
                        129.99f,
                        "Mesh Back Office Chair",
                        "C-225",
                        "White",
                        "Stay cool and comfortable with the Mesh Back Office Chair. Designed with breathable mesh, ergonomic lumbar support, and adjustable height, it is ideal for modern workspaces and home offices.",
                        "Chair",
                        90
                ),

                new Item(13,
                        R.drawable.chair6,
                        279.99f,
                        "Premium Recliner Chair",
                        "C-520",
                        "Brown",
                        "Relax in style with the Premium Recliner Chair. Built with plush cushioning, adjustable reclining positions, and a strong wooden frame, it offers superior comfort for lounging or reading.",
                        "Chair",
                        40
                ),
                new Item(14,
                        R.drawable.chair7,
                        159.99f,
                        "Modern Accent Chair",
                        "C-330",
                        "Green",
                        "Add elegance to your living space with the Modern Accent Chair. Featuring a sleek design, soft fabric upholstery, and solid wooden legs, it is perfect for lounges, bedrooms, or reception areas.",
                        "Chair",
                        70
                ),
                new Item(15,
                        R.drawable.keyboard5,
                        49.99f,
                        "Wireless Bluetooth Keyboard",
                        "K-205",
                        "White",
                        "Enjoy clutter-free typing with the Wireless Bluetooth Keyboard. Compatible with multiple devices, long battery life, and slim design make it ideal for work or study.",
                        "Keyboard",
                        80
                ),

                new Item(16,
                        R.drawable.keyboard6,
                        69.99f,
                        "Ergonomic Split Keyboard",
                        "K-310",
                        "Gray",
                        "Reduce strain on your wrists with the Ergonomic Split Keyboard. Its split layout, adjustable tenting, and soft key switches provide comfortable typing for long sessions.",
                        "Keyboard",
                        60
                ),

                new Item(17,
                        R.drawable.keyboard7,
                        89.99f,
                        "RGB Backlit Mechanical Keyboard",
                        "K-415",
                        "Black",
                        "A high-performance mechanical keyboard with vibrant RGB backlighting, programmable macros, and anti-ghosting features. Perfect for gamers and typists seeking precision and style.",
                        "Keyboard",
                        50
                ),
                new Item(18,
                        R.drawable.keyboard5,
                        59.99f,
                        "Compact Tenkeyless Keyboard",
                        "K-520",
                        "Black",
                        "Optimize your desk space with the Compact Tenkeyless Keyboard. Its minimalistic design, tactile key switches, and portable size make it ideal for gamers and professionals who prefer a clutter-free setup.",
                        "Keyboard",
                        70
                ),
                new Item(19,
                        R.drawable.led4,
                        19.99f,
                        "Standard LED Strip",
                        "L-201",
                        "White",
                        "A simple and reliable LED strip for ambient lighting. Easy to install and perfect for home or office decoration.",
                        "LED",
                        300
                ),

                new Item(20,
                        R.drawable.led5,
                        24.99f,
                        "Color-Changing LED Strip",
                        "L-202",
                        "Multicolor",
                        "Enhance any room with this color-changing LED strip. Features multiple modes and adjustable brightness for versatile lighting.",
                        "LED",
                        250
                ),

                new Item(21,
                        R.drawable.led6,
                        29.99f,
                        "USB-Powered LED Strip",
                        "L-203",
                        "Blue",
                        "Convenient USB-powered LED strip for desks, shelves, and entertainment areas. Compact and easy to use.",
                        "LED",
                        180
                ),

                new Item(22,
                        R.drawable.led7,
                        34.99f,
                        "Smart Wi-Fi LED Strip",
                        "L-204",
                        "RGB",
                        "Control lighting via smartphone or voice commands. Compatible with smart home systems for customizable ambiance.",
                        "LED",
                        120
                ),

                new Item(23,
                        R.drawable.led8,
                        39.99f,
                        "Premium Decorative LED Strip",
                        "L-205",
                        "Warm White",
                        "High-quality decorative LED strip with uniform brightness and flexible design. Ideal for accent lighting and home decoration.",
                        "LED",
                        100
                ),
                new Item(24,
                        R.drawable.mouse2,
                        39.99f,
                        "Wireless Ergonomic Mouse",
                        "M-205",
                        "Gray",
                        "Stay comfortable during long work sessions with the Wireless Ergonomic Mouse. Smooth tracking, adjustable DPI, and a sleek design make it perfect for office and home use.",
                        "Mouse",
                        120
                ),

                new Item(25,
                        R.drawable.mouse3,
                        49.99f,
                        "High-Precision Optical Mouse",
                        "M-310",
                        "White",
                        "Achieve accurate cursor control with the High-Precision Optical Mouse. Ideal for both gaming and professional tasks, featuring a responsive sensor and durable buttons.",
                        "Mouse",
                        100
                ),
                new Item(26,
                        R.drawable.mp1,
                        19.99f,
                        "Extended Gaming Mouse Pad",
                        "MP-101",
                        "Black",
                        "Upgrade your desk setup with the Extended Gaming Mouse Pad. Provides a smooth, consistent surface for precise mouse control, extra-large size to accommodate both keyboard and mouse, and a non-slip rubber base for stability during intense gaming sessions.",
                        "MousePad",
                        200
                ),
                new Item(27,
                        R.drawable.pc5,
                        1499.99f,
                        "Acer Mid-Range Gaming PC",
                        "PC-402",
                        "Gray",
                        "Powerful mid-range gaming PC featuring an Intel Core i7-12700K processor, 32GB DDR4 RAM, and an NVIDIA GeForce RTX 3070 GPU. Store your games on a 2TB SSD and enjoy smooth performance for both work and play.",
                        "PC",
                        60
                ),

                new Item(28,
                        R.drawable.pc6,
                        999.99f,
                        "HP Compact Gaming PC",
                        "PC-403",
                        "Black",
                        "Compact yet capable HP Gaming PC with Intel Core i5-12600K, 16GB RAM, and NVIDIA GeForce RTX 3060 GPU. Ideal for casual gaming and productivity tasks, with 1TB SSD storage for all your files.",
                        "PC",
                        80
                ),

                new Item(29,
                        R.drawable.pc7,
                        1299.99f,
                        "Dell Gaming Desktop",
                        "PC-404",
                        "White",
                        "Dell Gaming Desktop with AMD Ryzen 7 5800X processor, 32GB DDR4 RAM, and NVIDIA GeForce RTX 3070 GPU. Comes with 2TB SSD storage and optimized cooling for stable gaming sessions.",
                        "PC",
                        50
                )
        ));
        dodItems = new ArrayList<>(Arrays.asList(
                new Item(100,
                        R.drawable.microphone,
                        999.99f,
                        "Microphone",
                        "123-A",
                        "Black",
                        "A microphone is an essential audio device that captures sound waves and converts them into electrical signals for recording, amplification, or broadcasting. It allows for clear voice communication, high-quality audio recording, and seamless sound transmission in a variety of settings—whether in professional studios, live performances, podcasts, gaming, or virtual meetings. Modern microphones come in various types, including dynamic, condenser, and USB models, each designed to suit different audio needs. With features like noise cancellation, cardioid pickup patterns, and plug-and-play functionality, microphones ensure crisp, accurate, and reliable sound capture for both amateurs and professionals alike.",
                        899.99f,
                        "Microphone",
                        70
                ),
                new Item(101,
                        R.drawable.pc2,
                        1999.99f,
                        "MSI Gaming PC",
                        "M-123",
                        "Black",
                        "Dominate every game with the MSI Gaming PC. Equipped with an Intel Core i9-12900K processor, 32GB DDR5 RAM, and an NVIDIA GeForce RTX 4080 GPU, it delivers ultra-smooth gameplay and breathtaking visuals. Store all your games and files on a 2TB NVMe SSD while a 850W power supply ensures stable performance. With a sleek, gamer-focused design and advanced cooling system, the MSI Gaming PC keeps you in the action for hours without compromise.",
                        999.99f,
                        "PC",
                        50
                ),
                new Item(102,
                        R.drawable.chair1,
                        149.99f,
                        "Ergonomic Office Chair",
                        "C-201",
                        "Gray",
                        "Experience ultimate comfort with the Ergonomic Office Chair. Designed with adjustable lumbar support, breathable mesh back, and a cushioned seat, it ensures proper posture during long working hours. Featuring smooth-rolling wheels, a 360-degree swivel, and adjustable height, this chair is perfect for both home and office use.",
                        99.99f,
                        "Chair",
                        100
                ),
                new Item(103,
                        R.drawable.chair2,
                        249.99f,
                        "Luxury Gaming Chair",
                        "C-305",
                        "Red & Black",
                        "Level up your gaming setup with the Luxury Gaming Chair. Built with high-density foam padding, adjustable armrests, and a reclining backrest up to 180 degrees, it offers superior comfort and support. The sturdy metal frame and premium PU leather ensure durability, while the stylish racing design enhances your gaming experience.",
                        179.99f,
                        "Chair",
                        75
                ),
                new Item(104,
                        R.drawable.keyboard3,
                        79.99f,
                        "Mechanical Gaming Keyboard",
                        "K-101",
                        "Black",
                        "Enhance your gaming experience with the Mechanical Gaming Keyboard. Featuring customizable RGB lighting, tactile switches for responsive feedback, and durable build quality, this keyboard is perfect for competitive gaming.",
                        59.99f,
                        "Keyboard",
                        120
                ),
                new Item(105,
                        R.drawable.led2,
                        39.99f,
                        "RGB Gaming LED Strip",
                        "L-101",
                        "Multicolor",
                        "Illuminate your gaming setup with the RGB Gaming LED Strip. Features customizable lighting effects, easy installation, and dynamic color changes to enhance your gaming environment.",
                        29.99f,
                        "LED",
                        200
                ),
                new Item(106,
                        R.drawable.led3,
                        49.99f,
                        "High-Brightness Gaming LED Bar",
                        "L-102",
                        "RGB",
                        "Boost your gaming aesthetics with the High-Brightness Gaming LED Bar. Adjustable colors, responsive effects to music or games, and durable design make it perfect for immersive setups.",
                        39.99f,
                        "LED",
                        150
                ),
                new Item(107,
                        R.drawable.mouse1,
                        59.99f,
                        "RGB Gaming Mouse",
                        "M-101",
                        "Black",
                        "Enhance your gaming precision with the RGB Gaming Mouse. Features customizable DPI settings, programmable buttons, and dynamic RGB lighting to match your gaming setup.",
                        44.99f,
                        "Mouse",
                        150
                ),
                new Item(108,
                        R.drawable.pc4,
                        2199.99f,
                        "MSI High-End Gaming PC",
                        "PC-401",
                        "Black",
                        "Dominate every game with the MSI High-End Gaming PC. Equipped with an Intel Core i9-13900K processor, 64GB DDR5 RAM, and an NVIDIA GeForce RTX 4090 GPU, it delivers ultra-smooth gameplay and breathtaking visuals. Store all your games and files on a 4TB NVMe SSD while an 1000W power supply ensures stable performance. With a sleek, gamer-focused design and advanced cooling system, this PC keeps you in the action for hours without compromise.",
                        1999.99f,
                        "PC",
                        40
                )
        ));
        cart = new ArrayList<>();
        wishlist = new ArrayList<>();
        previousSearch = new ArrayList<>();
    }
}